import styles from './page.module.scss'
import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from './provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className={styles.content}>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  )
}
