import styles from './page.module.scss'
import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from './provider'
import {
  Hydrate,
  QueryClient,
  QueryClientProvider,
} from '@tanstack/react-query'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Hydrate >

            <div className={styles.content}>
              {children}
            </div>
          </Hydrate>
        </Providers>
      </body>
    </html>
  )
}
